### ISSUE TITLE
Suggestion: Give each div element the same class name, and each h2 element a unique id.

### ISSUE THREAD

**Issue by josephtkim** [sirusazadi/prj-rev-bwfs-dasmoto#3]
Since each div element should follow the same general structure and styling, they should be given the same class name. Each h2 element has unique styling, so it would be good to give them each a unique id name, like so

```html
  <div class="items">

    <h2 id="brushes">Brushes</h2>
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" />
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="blue"> Starting at $3.00 / brush.</span></p>

  </div>
```

id attributes are applied to individual elements when they have unique styling, and id names are unique and only applied to a single element in the entire document.  In contrast, class attributes are applied to multiple elements with shared styling.

**Comment by sirusazadi** [comment]
Yes makes sense. Thanks so much!
