### ISSUE TITLE
Suggestion: Give each img element an alt attribute

### ISSUE THREAD

**Issue by josephtkim** [sirusazadi/prj-rev-bwfs-dasmoto#4]
It can be a good idea to give image elements alt attributes, which act as placeholder text, descriptions, and also as additional text that search engines can use when finding matches. For instance,

```html
<img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" alt="Hacksaw Brush"/>
```

**Comment by sirusazadi** [comment]
Yes!
