### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [sirusazadi/prj-rev-bwfs-dasmoto#6]
**Grade: Meets Expectations**

**Summary:** Overall, I think you did a great job with your project implementation. The page design looks great, and seems to follow the layout and styling of the project spec guidelines. In addition, your code was very well structured and formatted, making it easily readable.

There were a few areas for improvement here. First is to give elements that share structure and styling a class name, like for each div element, and to give individual elements with unique styling an id name, like for each h2 element. Next, it is a good idea to give img elements alt attributes, which act as descriptions, placeholder text, and also provide additional text for search engines to find matches. Furthermore, it is good to try and simplify the CSS code as much as you can, so that the code is more concise and cleaner with less repeated code. 

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. You can take a look at these resources to get started - http://getbootstrap.com/ and https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Based on your work so far, I think you are up for the challenge. Keep up the great work!

**Comment by sirusazadi** [comment]
Thank you for constructive and informative feedback. I greatly appreciate it.
